#!/usr/bin/env bash
# Curation-time (NOT runtime) fetcher for the bundled logo pack (task 21,
# provider report v2 §11). Downloads favicons for the curated ticker list
# below into assets/logos/ and regenerates lib/data/market/company_logos.dart.
# Symbols whose favicon is missing or smaller than $MIN_SIZE px are skipped:
# they render the designed ticker-ring fallback instead.
#
# Run from the repo root on a network where Google is reachable; commit the
# resulting assets and Dart map. The app itself never fetches logos.
set -euo pipefail

MIN_SIZE=32
OUT_DIR="assets/logos"
DART_OUT="lib/data/market/company_logos.dart"

# "SYMBOL domain" — app-format symbols; domains are the companies' primary
# web homes (favicon quality was checked by eye when the pack was curated).
CURATED="
AAPL apple.com
MSFT microsoft.com
NVDA nvidia.com
GOOGL google.com
GOOG google.com
AMZN amazon.com
META meta.com
TSLA tesla.com
AVGO broadcom.com
BRK.B berkshirehathaway.com
LLY lilly.com
JPM jpmorganchase.com
V visa.com
MA mastercard.com
XOM exxonmobil.com
UNH unitedhealthgroup.com
JNJ jnj.com
WMT walmart.com
PG pg.com
HD homedepot.com
COST costco.com
ORCL oracle.com
MRK merck.com
CVX chevron.com
ABBV abbvie.com
KO coca-colacompany.com
PEP pepsico.com
ADBE adobe.com
BAC bankofamerica.com
CRM salesforce.com
NFLX netflix.com
AMD amd.com
TMO thermofisher.com
LIN linde.com
ACN accenture.com
MCD mcdonalds.com
CSCO cisco.com
ABT abbott.com
INTC intel.com
INTU intuit.com
DIS disney.com
WFC wellsfargo.com
QCOM qualcomm.com
IBM ibm.com
GE ge.com
CAT caterpillar.com
TXN ti.com
VZ verizon.com
AMGN amgen.com
PFE pfizer.com
NOW servicenow.com
UNP up.com
CMCSA comcast.com
PM pmi.com
SPGI spglobal.com
HON honeywell.com
COP conocophillips.com
UBER uber.com
GS goldmansachs.com
RTX rtx.com
NKE nike.com
LOW lowes.com
BA boeing.com
T att.com
ELV elevancehealth.com
BKNG booking.com
AXP americanexpress.com
PLD prologis.com
MS morganstanley.com
SBUX starbucks.com
ISRG intuitive.com
MDT medtronic.com
DE deere.com
BLK blackrock.com
TJX tjx.com
GILD gilead.com
LMT lockheedmartin.com
MMC marshmclennan.com
ADP adp.com
VRTX vrtx.com
BMY bms.com
SYK stryker.com
C citigroup.com
AMAT appliedmaterials.com
CVS cvshealth.com
MU micron.com
SCHW schwab.com
PANW paloaltonetworks.com
ANET arista.com
LRCX lamresearch.com
PYPL paypal.com
SHOP shopify.com
XYZ block.xyz
COIN coinbase.com
PLTR palantir.com
SNOW snowflake.com
ABNB airbnb.com
DASH doordash.com
RBLX roblox.com
HOOD robinhood.com
SOFI sofi.com
RIVN rivian.com
LCID lucidmotors.com
NIO nio.com
BABA alibabagroup.com
PDD pddholdings.com
JD jd.com
TSM tsmc.com
ASML asml.com
SMCI supermicro.com
ARM arm.com
MRVL marvell.com
DELL dell.com
HPQ hp.com
F ford.com
GM gm.com
UPS ups.com
FDX fedex.com
TMUS t-mobile.com
MO altria.com
MRNA modernatx.com
SPY ssga.com
DIA ssga.com
QQQ invesco.com
VOO vanguard.com
VTI vanguard.com
IWM ishares.com
"

mkdir -p "$OUT_DIR"
entries=()
skipped=()

while read -r symbol domain; do
  [[ -z "$symbol" ]] && continue
  file_name="$(echo "$symbol" | tr '[:upper:].' '[:lower:]-').png"
  path="$OUT_DIR/$file_name"
  code=$(curl -sL -o "$path" -w "%{http_code}" \
    "https://www.google.com/s2/favicons?domain=$domain&sz=128")
  if [[ "$code" != "200" ]]; then
    rm -f "$path"
    skipped+=("$symbol ($domain: HTTP $code)")
    continue
  fi
  width=$(sips -g pixelWidth "$path" 2>/dev/null | awk '/pixelWidth/ {print $2}')
  if [[ -z "$width" || "$width" -lt "$MIN_SIZE" ]]; then
    rm -f "$path"
    skipped+=("$symbol ($domain: ${width:-unreadable}px)")
    continue
  fi
  entries+=("  '$symbol': 'assets/logos/$file_name',")
done <<<"$CURATED"

{
  echo "// GENERATED by tool/fetch_logos.sh — edit the curated list there and re-run."
  echo ""
  echo "/// Bundled logo asset path for [symbol], or null: unmapped symbols render"
  echo "/// the ticker-ring fallback. Logos are build-time assets on purpose — no"
  echo "/// runtime logo host exists that is reliably reachable from both mainland"
  echo "/// China and the US (provider report v2 §11)."
  echo "String? companyLogoAsset(String symbol) => companyLogoAssets[symbol];"
  echo ""
  echo "/// The full curated pack, keyed by app symbol; exposed so tests can"
  echo "/// verify every entry points at a bundled file."
  echo "const companyLogoAssets = <String, String>{"
  printf '%s\n' "${entries[@]}" | sort
  echo "};"
} >"$DART_OUT"

echo "bundled: ${#entries[@]}"
echo "skipped: ${#skipped[@]}"
printf '  %s\n' "${skipped[@]}"
